"""admin migration

Revision ID: 2be75897eaa6
Revises: 25c4e65d8e2c
Create Date: 2024-07-21 06:22:20.380865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be75897eaa6'
down_revision = '25c4e65d8e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips_users', schema=None) as batch_op:
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'planned_trips', ['trip_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('trips_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'planned_trips', ['trip_id'], ['id'])
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
