"""add-plannedTrip

Revision ID: 89219705fd61
Revises: bc59fa28e817
Create Date: 2024-07-09 21:51:48.443411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89219705fd61'
down_revision = 'bc59fa28e817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('destination', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_trip')
    # ### end Alembic commands ###
